# Generated by Django 2.1 on 2021-01-31 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmcName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='broadcastmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Broadcast Messages',
            },
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_status', models.CharField(max_length=50)),
                ('smstype', models.CharField(max_length=50)),
                ('total_sent', models.CharField(max_length=50)),
                ('total_rejected', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('credit_used', models.CharField(max_length=50)),
                ('credit_left', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('EmpNumber', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=11)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('OtherName', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('DOB', models.DateField()),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('Religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=10)),
                ('OfficialEmail', models.CharField(max_length=50, unique=True)),
                ('PersonalEmail', models.CharField(max_length=50, unique=True)),
                ('Mobile', models.CharField(max_length=10, unique=True)),
                ('Mobile1', models.CharField(max_length=10, unique=True)),
                ('FirstAppDate', models.DateField()),
                ('AssumptionDutyDate', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bmc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.bmc')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.grade')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.group')),
            ],
            options={
                'verbose_name_plural': 'records',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdistrictName', models.CharField(max_length=50)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.unit'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.region'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.group'),
        ),
        migrations.AddField(
            model_name='bmc',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.subdistrict'),
        ),
    ]
