# Generated by Django 2.1 on 2021-02-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_auto_20210215_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
