# Generated by Django 2.1 on 2021-02-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_auto_20210215_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Mobile1',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='OfficialEmail',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='OtherName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='records',
            name='PersonalEmail',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='Religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='Title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=11),
        ),
    ]
