# Generated by Django 2.1 on 2021-02-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_auto_20210215_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='AssumptionDutyDate',
            field=models.DateField(verbose_name='Date of Assumption of Duty'),
        ),
        migrations.AlterField(
            model_name='records',
            name='DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='records',
            name='EmpNumber',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Employment Number'),
        ),
        migrations.AlterField(
            model_name='records',
            name='FirstAppDate',
            field=models.DateField(verbose_name='First Appointment Date'),
        ),
        migrations.AlterField(
            model_name='records',
            name='FirstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='LastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='MaritalStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='records',
            name='Mobile',
            field=models.CharField(max_length=10, unique=True, verbose_name='1st Mobile'),
        ),
        migrations.AlterField(
            model_name='records',
            name='Mobile1',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='2nd Mobile'),
        ),
        migrations.AlterField(
            model_name='records',
            name='OfficialEmail',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='records',
            name='OtherName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='PersonalEmail',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='records',
            name='bmc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.bmc', verbose_name='BMC'),
        ),
    ]
