# Generated by Django 2.1 on 2021-02-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_auto_20210215_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmc',
            options={'ordering': ('bmcName',)},
        ),
    ]
