# Generated by Django 2.1 on 2021-02-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0007_auto_20210217_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade',)},
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='criteria',
            field=models.CharField(default='District', max_length=10),
        ),
    ]
