# Generated by Django 2.1 on 2021-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_auto_20210220_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='criteria',
            field=models.CharField(choices=[('District', 'District'), ('Category', 'Category')], default='District', max_length=10),
        ),
    ]
