# Generated by Django 2.1 on 2021-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0012_auto_20211205_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadcastmessageall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Broadcast Messages to all',
            },
        ),
        migrations.AlterModelOptions(
            name='broadcastmessagecat',
            options={'verbose_name_plural': 'Category-based Broadcast Messages'},
        ),
        migrations.AlterModelOptions(
            name='broadcastmessagedis',
            options={'verbose_name_plural': 'District-based Broadcast Messages'},
        ),
    ]
