# Generated by Django 2.1 on 2022-03-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0013_auto_20211205_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='MaritalStatus',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='records',
            name='Mobile1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='2nd Mobile'),
        ),
        migrations.AlterField(
            model_name='records',
            name='OfficialEmail',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='records',
            name='OtherName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='records',
            name='PersonalEmail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='records',
            name='Title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.unit'),
        ),
    ]
